version: '3'

output: 'group'
silent: true

vars:

  BUILD_DIR: 'build'
  # not sure how else to version tools which need to be build as part of different project
  PRJ_VERSION: '{{default "v1.0.1" (env "PRJ_VERSION")}}'

  GO_VERSION_MIN_REQUIRED: '1.23.3'

  GO_VERSION_FULL: {sh: go version}
  GO_VERSION: '{{regexFind "[0-9]+\\.[0-9]+\\.?[0-9]*" (regexFind "go version go[0-9]+\\.[0-9]+\\.?[0-9]*[a-zA-Z0-9]* [^/]+/.*" .GO_VERSION_FULL)}}'
  GO_VERSION_LANG: '{{regexFind "[0-9]+\\.[0-9]+" .GO_VERSION}}'

  TATN: {sh: '{{if (env "TERM")}}tput setaf 4{{end}}'}
  TOFF: {sh: '{{if (env "TERM")}}tput sgr0{{end}}'}

env:
  CGO_ENABLED: '0'
  GOPATH: '{{default "/tmp/gopkg_gencfg_{{.GO_VERSION}}" (env "GOPATH")}}'
  # After go1.21 lock everything to locally installed go version to prevent automatic caching and usage of multiple go versions
  GOTOOLCHAIN: 'local+path'

tasks:

  default:
    desc: Builds local development version and updates artifacts (if necessary) for release build
    aliases: [debug]
    deps:
      - task: copy-file
        vars: {SRC: 'scripts/git/pre-commit', DST: '.git/hooks/pre-commit'}
      - task: copy-file
        vars: {SRC: 'scripts/git/pre-push', DST: '.git/hooks/pre-push'}
      - task: check-go-version
      - task: generate-project-versions
    cmds:
      - task: go-build
        vars: {FLAG: 'debug', PACKAGE: './cmd/tool', TARGET: '{{.BUILD_DIR}}/gencfg'}
      - task: compile-all-tests
      - task: lint

  release:
    desc: Builds release version
    deps: [check-go-version, generate-project-versions]
    cmds:
      - task: go-build
        vars: {FLAG: 'release', PACKAGE: './cmd/tool', TARGET: '{{.BUILD_DIR}}/gencfg'}

  test:
    desc: |
      Runs available tests
          When invoked as usual runs tests for all packages where it can find "*_test.go" files, for example: "task test"
          You can specify what tests to run by using PACKAGES environment variable, for example: "PACKAGES='./module1,./module2' task test"
          You can pass any additional parameters supported by "go test", for example: "PACKAGES='./module1' task test -- -run=TestFunc"
    deps: [check-go-version, generate-project-versions]
    vars:
      TEST_DIR: '{{.ROOT_DIR}}/{{.BUILD_DIR}}/tests_results'
      DIRS_WITH_TESTS:
        sh: find -name '*_test.go' -printf "%h\n" | sort -u
      PACKAGES: '{{default .DIRS_WITH_TESTS (replace "," "\n" (env "PACKAGES"))}}'
    env:
      CGO_ENABLED: '1'
    cmds:
      - mkdir -p {{.TEST_DIR}}
      - for: {var: PACKAGES}
        cmd: |
          echo
          echo "{{.TATN}}gencfg{{if (ne (clean .ITEM) ".")}} {{clean .ITEM}}{{end}} tests...{{.TOFF}}"
          echo
          go test -mod=mod -v -coverprofile='{{.TEST_DIR}}/test_{{replace "/" "_" (clean .ITEM)}}_coverage.out' {{.CLI_ARGS}} '{{.ITEM}}'

  clean:
    desc: Removes build artifacts and task's checksums
    cmds:
      - rm -rfv '{{.BUILD_DIR}}'
      - rm -rfv '_obj'
      - rm -fv .task/checksum/*
      - rm -fv .task/timestamp/*
      - rm -fv misc/version.go

  lint:
    internal: true
    desc: Lints the whole project
    vars:
      LINTER: '{{.BUILD_DIR}}/staticcheck'
    cmds:
      - task: build-linter
        vars: {LINTER: '{{.LINTER}}'}
      - echo "{{.TATN}}Linting project{{.TOFF}}"
      - ./{{.LINTER}} -f stylish -tests=false ./...
    sources:
      - ./**/*.go
      - ./go.sum
      - ./go.mod

  go-tidy:
    desc: Tidy Go modules for the project
    aliases: [tidy]
    deps: [check-go-version]
    vars:
      SUPPORTED_GO_VER: '{{default "" (regexFind "[0-9]+\\.[0-9]+" .GO_VERSION_MIN_REQUIRED)}}'
    cmds:
      - echo "{{.TATN}}Running go tidy with{{if .SUPPORTED_GO_VER}} -go={{.SUPPORTED_GO_VER}}{{end}}{{.TOFF}}"
      - go mod tidy{{if .SUPPORTED_GO_VER}} -go={{.SUPPORTED_GO_VER}}{{end}}

  build-linter:
    internal: true
    desc: Builds linter for the project
    requires:
      vars: [LINTER]
    cmds:
      - task: go-build-tool
        vars: {PACKAGE: 'honnef.co/go/tools/cmd/staticcheck', TARGET: '{{.LINTER}}'}
    sources:
      - tools/tools.go
      - go.mod
      - go.sum
    generates:
      - '{{.LINTER}}'

  compile-all-tests:
    internal: true
    run: when_changed
    desc: Makes sure that tests could be compiled successfully
    env:
      CGO_ENABLED: '1'
    vars:
      DIRS_WITH_TESTS:
        sh: find -name '*_test.go' -printf "%h\n" | sort -u
    cmds:
      - echo "{{.TATN}}Check compiling all availble tests{{.TOFF}}"
      - for: {var: DIRS_WITH_TESTS, as: DIR}
        cmd: go test -mod=mod -c -o /dev/null '{{.DIR}}'
    sources:
      - ./**/*.go

  check-go-version:
    internal: true
    run: once
    desc: Validates that minimal Go version requirement is met and updates required files accordingly
    preconditions:
      - sh: scripts/bash/vercmp.sh {{.GO_VERSION}} gteq {{.GO_VERSION_MIN_REQUIRED}}
        msg: "At least {{.GO_VERSION_MIN_REQUIRED}} of go is required, but {{.GO_VERSION}} is detected!"

  go-build:
    internal: true
    run: when_changed
    desc: Builds binary using go toolchain
    label: go-build-{{.PACKAGE}}-{{.TARGET}}-{{.FLAG}}
    requires:
      vars: [FLAG, PACKAGE, TARGET]
    vars:
      GOARGS: |
        {{- if eq .FLAG "debug" -}}
          -mod=mod -gcflags 'all=-N -l'
        {{- else if eq .FLAG "release" -}}
          -mod=mod -trimpath
        {{- else -}}
        {{fail "go build flags could be \"debug\", \"release\" or \"xtool\" only!"}}
        {{- end -}}
    cmds:
      - echo "{{.TATN}}Building \"{{base .TARGET}}\" binary from \"{{.PACKAGE}}\"{{.TOFF}}"
      - go build {{.GOARGS}} -tags '{{.FLAG}}' -o '{{.TARGET}}' '{{.PACKAGE}}'
    sources:
      - ./**/*.go
    generates:
      - '{{.TARGET}}'
    status:
      # NOTE: since we are using the same build directory for debug and release builds of the same binary (different
      # compiler options the same sources) we need an additional check here
      - go version -m '{{.TARGET}}' | grep -q -e '-tags={{.FLAG}}'

  go-build-tool:
    internal: true
    run: when_changed
    desc: Builds binary using go toolchain.
    label: go-build-tool-{{.PACKAGE}}-{{.TARGET}}
    requires:
      vars: [PACKAGE, TARGET]
    cmds:
      - echo "{{.TATN}}Building \"{{base .TARGET}}\" binary from \"{{.PACKAGE}}\"{{.TOFF}}"
      - go build -mod=mod -trimpath -o '{{.TARGET}}' '{{.PACKAGE}}'
    sources:
      - ./**/*.go
    generates:
      - '{{.TARGET}}'

  generate-project-versions:
    internal: true
    desc: Generates "misc/version.go" file with version info to be used on runtime
    run: when_changed
    vars:
      DIR: '{{.ROOT_DIR}}/misc'
      FILE: '{{.DIR}}/version.go'
    cmds:
      - echo "{{.TATN}}Project version {{.PRJ_VERSION}}, git {{.GIT_HASH}}{{if .GIT_STATUS}}*{{end}}{{.TOFF}}"
      - mkdir -p {{.DIR}}
      - |
        cat << EOF > {{.FILE}}
        // Code generated by build tools. DO NOT EDIT.

        package misc

        const(
          AppName = "gencfg"
        )

        func GetVersion() string {
            return "{{.PRJ_VERSION}}"
        }
        EOF
      - gofmt -w {{.FILE}}
    sources:
      - .git/index
    generates:
      - '{{.FILE}}'

  copy-file:
    internal: true
    desc: Copies source file to destination
    requires:
      vars: [SRC, DST]
    label: copy-file-{{.SRC}}-{{.DST}}
    cmds:
      - echo "{{.TATN}}Copying \"{{.SRC}}\" to \"{{.DST}}\"{{.TOFF}}"
      - mkdir -p {{dir .DST}}
      - cp '{{.SRC}}' '{{.DST}}'
    sources:
      - '{{.SRC}}'
    generates:
      - '{{.DST}}'
    status:
      - test -f '{{.DST}}'
    method: timestamp
